sudo: false
language: python
cache:
  directories:
    - .tox
    - tests/testdata
python:
  - "2.7"
  - "3.5"
#  - "3.7"  # Python 3.7 is not available on travis CI yet
install:
  - pip install tox-travis
  - sh get_testdata.sh
script: tox
